version: '3.9'

services:
  backend:
    build:
      context: ./project/backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: maxscale
      DB_PORT: 3306
      DB_USER: your_database_user
      DB_PASSWORD: your_database_password
      DB_NAME: your_database_name
      OIDC_ISSUER_URL: http://keycloak:8080/realms/myrealm
      OIDC_CLIENT_ID: backend-client
      OIDC_CLIENT_SECRET: your_client_secret
    networks:
      - webnet
    depends_on:
      - maxscale
      - keycloak

  frontend:
    build:
      context: ./project/frontend
    ports:
      - "8080:80"
    environment:
      NODE_ENV: production
      REACT_APP_OIDC_ISSUER: http://keycloak:8080/realms/myrealm
      REACT_APP_OIDC_CLIENT_ID: frontend-client
    networks:
      - webnet

  database1:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    volumes:
      - db1-data:/var/lib/mysql
      - ./database1-init:/docker-entrypoint-initdb.d
    networks:
      - webnet
    ports:
      - "3307:3306"

  database2:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    volumes:
      - db2-data:/var/lib/mysql
      - ./database2-init:/docker-entrypoint-initdb.d
    networks:
      - webnet
    ports:
      - "3308:3306"

  database3:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password
    volumes:
      - db3-data:/var/lib/mysql
      - ./database3-init:/docker-entrypoint-initdb.d
    networks:
      - webnet
    ports:
      - "3309:3306"

  maxscale:
    image: mariadb/maxscale:latest
    build:
      context: ./maxscale
    ports:
      - "3310:3306"
    networks:
      - webnet
    depends_on:
      - database1
      - database2
      - database3

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=h2
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    command: ["start-dev"]
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak-data:/opt/keycloak/data
    networks:
      - webnet

networks:
  webnet:

volumes:
  db1-data:
  db2-data:
  db3-data:
